# Generated by Django 2.2.12 on 2020-05-11 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0008_auto_20210225_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to=settings.AUTH_USER_MODEL),
        ),
    ]
